version: '3.7'

services:
  neo4j:
    image: neo4j:5.3.0
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/testpassword
    ports:
      - "7474:7474"   # HTTP access
      - "7687:7687"   # Bolt access
    volumes:
      - neo4j_data:/data

  api:
    build: ./api
    container_name: umbrix-backend
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testpassword
    ports:
      - "5000:5000"
    depends_on:
      - neo4j

volumes:
  neo4j_data:

